apiVersion: v1
kind: Service
metadata:
  name: todo-manager-service
  namespace: todo-app
spec:
  selector:
    app: todo-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
